# Generated by Django 6.0 on 2026-04-16 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('ideas', '0001_initial'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='ideas.idea'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='ideas.season'),
        ),
        migrations.AddField(
            model_name='evaluationassignment',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationassignment',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_assignments', to='ideas.idea'),
        ),
        migrations.AddField(
            model_name='evaluationassignment',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_assignments', to='ideas.season'),
        ),
        migrations.AddField(
            model_name='evaluationinvitation',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_invitations', to='ideas.season'),
        ),
        migrations.AddField(
            model_name='evaluationinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationassignment',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='evaluations.evaluationinvitation'),
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluationcriterion'),
        ),
        migrations.AddField(
            model_name='evaluationscore',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='incubationassignment',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incubation_assignments', to='ideas.idea'),
        ),
        migrations.AddField(
            model_name='incubationassignment',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteerprofile'),
        ),
        migrations.AddField(
            model_name='incubationreview',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incubationreview',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ideas.idea'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('evaluator', 'idea', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationassignment',
            unique_together={('evaluator', 'idea', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationscore',
            unique_together={('evaluation', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='incubationassignment',
            unique_together={('idea', 'mentor')},
        ),
    ]
