# Generated by Django 6.0.3 on 2026-04-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_evaluationassignment_meeting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
