# Generated by Django 6.0.3 on 2026-04-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubationassignment',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
