# Generated by Django 6.0 on 2026-05-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationnote',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
