# Generated by Django 6.0.3 on 2026-04-12 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
        ('ideas', '0002_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncubationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incubation_assignments', to='ideas.idea')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteerprofile')),
            ],
            options={
                'unique_together': {('idea', 'mentor')},
            },
        ),
    ]
