# Generated by Django 6.0.3 on 2026-04-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_incubationassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationinvitation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationinvitation',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
