# Generated by Django 6.0.3 on 2026-04-29 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_incubationassignment_meeting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incubationreview',
            name='meeting_date',
        ),
        migrations.AddField(
            model_name='incubationreview',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incubationreview',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incubationreview',
            name='progress_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
