# Generated by Django 6.0 on 2026-05-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_evaluationinvitation_created_by_evaluationnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubationreview',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
