# Generated by Django 6.0 on 2026-05-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_incubationreview_meeting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incubationreview',
            name='meeting_date',
        ),
    ]
