# Generated by Django 6.0.3 on 2026-04-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_evaluationinvitation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationinvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='PENDING', max_length=10),
        ),
    ]
