# Generated by Django 6.0.3 on 2026-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_remove_incubationreview_meeting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationinvitation',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
