# Generated by Django 6.0.3 on 2026-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_remove_incubationreview_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationinvitation',
            name='expertise_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
