# Generated by Django 6.0.3 on 2026-04-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_evaluationtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTemplateCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationcriterion')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='evaluations.evaluationtemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'criterion')},
            },
        ),
    ]
