# Generated by Django 6.0.3 on 2026-04-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_evaluationtemplatecriterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationscore',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
