# Generated by Django 6.0 on 2026-06-18 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20)),
                ('residence', models.CharField(max_length=255)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('primary_skills', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('ui_ux', 'UI/UX'), ('business', 'Business'), ('marketing', 'Marketing'), ('legal', 'Legal')], max_length=50)),
                ('additional_skills', models.JSONField(blank=True, default=list)),
                ('volunteer_type', models.JSONField(blank=True, default=list, help_text='استشارات، تنفيذ مهام تقنية، مدرب')),
                ('availability_type', models.CharField(help_text='تعاون طويل / تعاون محدود', max_length=50)),
                ('motivation', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='volunteer_cvs/')),
                ('current_company', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('projects_count', models.PositiveBigIntegerField(null=True)),
                ('bio', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_type', models.CharField(blank=True, choices=[('ONE_TIME', 'استشارة لمرة واحدة'), ('ONGOING', 'متابعة دورية')], max_length=20, null=True)),
                ('required_skill', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='ideas.idea')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_consultation_requests', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='volunteers.volunteerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.CharField(choices=[('SUNDAY', 'الأحد'), ('MONDAY', 'الاثنين'), ('TUESDAY', 'الثلاثاء'), ('WEDNESDAY', 'الأربعاء'), ('THURSDAY', 'الخميس'), ('FRIDAY', 'الجمعة'), ('SATURDAY', 'السبت')], max_length=15, null=True)),
                ('end_day', models.CharField(choices=[('SUNDAY', 'الأحد'), ('MONDAY', 'الاثنين'), ('TUESDAY', 'الثلاثاء'), ('WEDNESDAY', 'الأربعاء'), ('THURSDAY', 'الخميس'), ('FRIDAY', 'الجمعة'), ('SATURDAY', 'السبت')], max_length=15, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='volunteers.volunteerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('target_audience', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.JSONField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('sessions', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshops/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_workshops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SUNDAY', 'الأحد'), ('MONDAY', 'الاثنين'), ('TUESDAY', 'الثلاثاء'), ('WEDNESDAY', 'الأربعاء'), ('THURSDAY', 'الخميس'), ('FRIDAY', 'الجمعة'), ('SATURDAY', 'السبت')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='volunteers.volunteerprofile')),
            ],
            options={
                'unique_together': {('volunteer', 'day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('tasks', models.TextField(max_length=100, null=True)),
                ('required_skill', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='ideas.idea')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_join_requests', to=settings.AUTH_USER_MODEL)),
                ('team_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.teamrequest')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='volunteers.volunteerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('requester', 'volunteer'), name='unique_pending_join_request')],
            },
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='volunteers.workshop')),
            ],
            options={
                'unique_together': {('user', 'workshop')},
            },
        ),
    ]
