# Generated by Django 6.0 on 2026-01-27 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20)),
                ('residence', models.CharField(max_length=255)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('primary_skills', models.TextField()),
                ('additional_skills', models.TextField(blank=True)),
                ('volunteer_type', models.CharField(help_text='استشارات، تقني، مدرب...', max_length=100)),
                ('availability_type', models.CharField(help_text='تعاون طويل / تعاون محدود', max_length=50)),
                ('motivation', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='volunteer_cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SUNDAY', 'الأحد'), ('MONDAY', 'الاثنين'), ('TUESDAY', 'الثلاثاء'), ('WEDNESDAY', 'الأربعاء'), ('THURSDAY', 'الخميس'), ('FRIDAY', 'الجمعة'), ('SATURDAY', 'السبت')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='volunteers.volunteerprofile')),
            ],
            options={
                'unique_together': {('volunteer', 'day', 'start_time', 'end_time')},
            },
        ),
    ]
