# Generated by Django 6.0 on 2026-05-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='projects_count',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
