# Generated by Django 6.0.3 on 2026-04-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
