# Generated by Django 6.0.3 on 2026-04-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteerprofile_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='additional_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
