# Generated by Django 6.0 on 2026-05-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_joinrequest_unique_pending_join_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.JSONField(),
        ),
    ]
