# Generated by Django 6.0 on 2026-04-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteerprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteervacation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='volunteervacation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='volunteervacation',
            name='end_day',
            field=models.CharField(choices=[('SUNDAY', 'الأحد'), ('MONDAY', 'الاثنين'), ('TUESDAY', 'الثلاثاء'), ('WEDNESDAY', 'الأربعاء'), ('THURSDAY', 'الخميس'), ('FRIDAY', 'الجمعة'), ('SATURDAY', 'السبت')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='volunteervacation',
            name='start_day',
            field=models.CharField(choices=[('SUNDAY', 'الأحد'), ('MONDAY', 'الاثنين'), ('TUESDAY', 'الثلاثاء'), ('WEDNESDAY', 'الأربعاء'), ('THURSDAY', 'الخميس'), ('FRIDAY', 'الجمعة'), ('SATURDAY', 'السبت')], max_length=15, null=True),
        ),
    ]
