# Generated by Django 6.0 on 2026-05-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteerprofile_projects_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
