# Generated by Django 6.0 on 2026-03-24 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_consultationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='requester_email',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='requester_name',
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VolunteerJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(max_length=254)),
                ('project_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_audience', models.TextField(blank=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='volunteers.volunteerprofile')),
            ],
        ),
    ]
