# Generated by Django 6.0 on 2026-03-24 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_remove_consultationrequest_requester_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='request_type',
            field=models.CharField(choices=[('CONSULTATION', 'استشارة'), ('JOIN', 'انضمام لفريق')], default='CONSULTATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_consultation_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
