# Generated by Django 6.0 on 2026-05-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_workshop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='objectives',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
