# Generated by Django 6.0 on 2026-05-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_volunteerprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='primary_skills',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('ui_ux', 'UI/UX'), ('business', 'Business'), ('marketing', 'Marketing'), ('legal', 'Legal')], max_length=50),
        ),
    ]
