# Generated by Django 6.0 on 2026-04-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_remove_volunteervacation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='sessions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.CharField(),
        ),
    ]
