# Generated by Django 6.0 on 2026-05-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_alter_workshop_description_alter_workshop_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='volunteer_type',
            field=models.JSONField(blank=True, default=list, help_text='استشارات، تنفيذ مهام تقنية، مدرب'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
