# Generated by Django 6.0 on 2026-04-25 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def migrate_join_requests(apps, schema_editor):
    ConsultationRequest = apps.get_model("volunteers", "ConsultationRequest")
    JoinRequest = apps.get_model("volunteers", "JoinRequest")

    join_requests = ConsultationRequest.objects.filter(request_type="JOIN")

    for jr in join_requests:
        # حماية من القيم الناقصة
        if not jr.team_request:
            continue

        JoinRequest.objects.create(
            volunteer=jr.volunteer,
            requester=jr.requester,
            idea=jr.idea,
            team_request=jr.team_request,
            description=jr.description,
            status=jr.status,
            created_at=jr.created_at,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_ideaauditlog_reason'),
        ('volunteers', '0004_workshop_sessions_alter_workshop_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='help_type',
            field=models.CharField(blank=True, choices=[('ONE_TIME', 'استشارة لمرة واحدة'), ('ONGOING', 'متابعة دورية')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('ACCEPTED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='ideas.idea')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_join_requests', to=settings.AUTH_USER_MODEL)),
                ('team_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.teamrequest')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='volunteers.volunteerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(migrate_join_requests),
    ]
