# Generated by Django 6.0 on 2026-04-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_consultationrequest_help_type_joinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='duration',
        ),
    ]
