# Generated by Django 6.0 on 2026-03-25 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_alter_formquestion_type'),
        ('volunteers', '0005_alter_consultationrequest_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='consultation_type',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='project_title',
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='ideas.idea'),
        ),
    ]
