# Generated by Django 6.0.3 on 2026-04-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_remove_consultationrequest_consultation_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
