# Generated by Django 6.0 on 2026-04-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_remove_idea_bootcamp_status_and_more'),
        ('volunteers', '0006_remove_consultationrequest_consultation_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='team_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.teamrequest'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='ideas.idea'),
        ),
        migrations.DeleteModel(
            name='VolunteerJoinRequest',
        ),
    ]
