# Generated by Django 6.0 on 2026-04-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_remove_workshop_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='team_request',
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='required_skill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='required_skill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='tasks',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
