# Generated by Django 6.0 on 2026-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='consultation_field',
            field=models.CharField(blank=True, choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('ui_ux', 'UI/UX'), ('business', 'Business'), ('marketing', 'Marketing'), ('legal', 'Legal')], max_length=50),
        ),
    ]
