# Generated by Django 6.0 on 2026-04-16 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select (single)'), ('select_multiple', 'Select (multiple)'), ('boolean', 'Yes / No')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_open', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('exhibition_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='MEMBER', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skill_required', models.CharField(max_length=255)),
                ('members_needed', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select (single)'), ('select_multiple', 'Select (multiple)'), ('boolean', 'Yes / No')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ideas.exhibitionform')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ideas.exhibitionquestion')),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='ideas.formquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('WITHDRAWN', 'Withdrawn'), ('PRE_ACCEPTED', 'Pre Accepted (Bootcamp)'), ('BOOTCAMP', 'In Bootcamp'), ('BOOTCAMP_FAILED', 'Bootcamp Failed'), ('EVALUATION', 'In Evaluation'), ('EVALUATED', 'Evaluated'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('INCUBATION', 'In Incubation'), ('EXHIBITION', 'In Exhibition'), ('GRADUATED_POSITIVE', 'Graduated (Positive)'), ('GRADUATED_NEGATIVE', 'Graduated (Negative)')], default='DRAFT', max_length=50)),
                ('team_status', models.CharField(choices=[('no_team', 'No Team'), ('team_building', 'Building Team'), ('team_full', 'Team Complete'), ('in_progress', 'In Progress')], default='no_team', max_length=50)),
                ('answers', models.JSONField(default=dict)),
                ('sector', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('exhibition_image', models.ImageField(blank=True, null=True, upload_to='exhibition/')),
                ('project_goal', models.TextField(blank=True, null=True)),
                ('project_services', models.TextField(blank=True, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('team_emails', models.TextField(blank=True, null=True)),
                ('exhibition_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ideas', to='ideas.season')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ideas.idea')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='formquestion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ideas.ideaform'),
        ),
        migrations.AddField(
            model_name='ideaform',
            name='season',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='ideas.season'),
        ),
        migrations.AddField(
            model_name='exhibitionform',
            name='season',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_form', to='ideas.season'),
        ),
        migrations.CreateModel(
            name='SeasonPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('SUBMISSION', 'Submission'), ('BOOTCAMP', 'Bootcamp'), ('EVALUATION', 'Evaluation'), ('INCUBATION', 'Incubation'), ('EXHIBITION', 'Exhibition')], max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('order', models.PositiveIntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='ideas.season')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
