# Generated by Django 6.0 on 2026-02-04 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('SUBMISSION', 'Submission'), ('BOOTCAMP', 'Bootcamp'), ('EVALUATION', 'Evaluation'), ('INCUBATION', 'Incubation'), ('EXHIBITION', 'Exhibition')], max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('order', models.PositiveIntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='ideas.season')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('season', 'phase')},
            },
        ),
    ]
