# Generated by Django 6.0 on 2026-04-16 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0001_initial'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedvolunteer',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteerprofile'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='ideas.idea'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to='ideas.idea'),
        ),
        migrations.AddField(
            model_name='suggestedvolunteer',
            name='team_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_volunteers', to='ideas.teamrequest'),
        ),
        migrations.AddConstraint(
            model_name='exhibitionquestion',
            constraint=models.UniqueConstraint(fields=('form', 'key'), name='unique_exhibition_question_key_per_form'),
        ),
        migrations.AddConstraint(
            model_name='formquestionchoice',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='unique_choice_value_per_question'),
        ),
        migrations.AddConstraint(
            model_name='formquestion',
            constraint=models.UniqueConstraint(fields=('form', 'key'), name='unique_question_key_per_form'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonphase',
            unique_together={('season', 'phase')},
        ),
    ]
