# Generated by Django 6.0.3 on 2026-05-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionform',
            name='title',
            field=models.CharField(default='بطاقة المعرض', max_length=255),
        ),
    ]
