# Generated by Django 6.0 on 2026-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
