# Generated by Django 6.0 on 2026-05-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrequest',
            name='skill_required',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
