# Generated by Django 6.0 on 2026-05-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='exhibition_date',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='exhibition_image',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='project_goal',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='project_services',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='team_emails',
        ),
    ]
