# Generated by Django 6.0 on 2026-06-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select (single)'), ('select_multiple', 'Select (multiple)'), ('boolean', 'Yes / No'), ('list_text', 'List Text'), ('radio', 'Radio')], max_length=20),
        ),
    ]
