# Generated by Django 6.0.3 on 2026-04-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='exhibition_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
