# Generated by Django 6.0 on 2026-06-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionquestion',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select (single)'), ('select_multiple', 'Select (multiple)'), ('boolean', 'نعم\\لا'), ('list_text', 'List Text')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select (single)'), ('select_multiple', 'Select (multiple)'), ('boolean', 'نعم / لا'), ('list_text', 'List Text')], max_length=20),
        ),
    ]
