# Generated by Django 6.0 on 2026-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_formquestion_help_text_formquestion_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideaauditlog',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
