# Generated by Django 6.0.3 on 2026-04-16 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_season_exhibition_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_form', to='ideas.season')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select (single)'), ('select_multiple', 'Select (multiple)'), ('boolean', 'Yes / No')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ideas.exhibitionform')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ideas.exhibitionquestion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exhibitionquestion',
            constraint=models.UniqueConstraint(fields=('form', 'key'), name='unique_exhibition_question_key_per_form'),
        ),
    ]
