# Generated by Django 6.0 on 2026-05-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_remove_idea_exhibition_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formquestion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='formquestion',
            name='source',
            field=models.CharField(choices=[('STATIC', 'Static'), ('DYNAMIC', 'Dynamic')], default='DYNAMIC', max_length=20),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='static_field',
            field=models.CharField(blank=True, choices=[('title', 'Title'), ('description', 'Description'), ('target_audience', 'Target Audience'), ('sector', 'Sector')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select (single)'), ('select_multiple', 'Select (multiple)'), ('boolean', 'Yes / No'), ('list_text', 'List Text')], max_length=20),
        ),
        migrations.CreateModel(
            name='FormStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ideas.ideaform')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='formquestion',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ideas.formstep'),
        ),
        migrations.AddConstraint(
            model_name='formquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'STATIC')), fields=('form', 'static_field'), name='unique_static_field_per_form'),
        ),
        migrations.AlterUniqueTogether(
            name='formstep',
            unique_together={('form', 'order')},
        ),
    ]
