# Generated by Django 6.0 on 2026-06-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_formquestion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionquestion',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select (single)'), ('select_multiple', 'Select (multiple)'), ('boolean', 'Yes / No'), ('image', 'Image')], max_length=20),
        ),
    ]
