# Generated by Django 6.0.3 on 2026-04-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_season_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonphase',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonphase',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
