# Generated by Django 6.0 on 2026-03-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_formquestionchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select (single)'), ('select_multiple', 'Select (multiple)'), ('boolean', 'Yes / No')], max_length=20),
        ),
    ]
