# Generated by Django 6.0.3 on 2026-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_exhibitionsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitionsubmission',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibitionsubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
