# Generated by Django 6.0 on 2026-03-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='exhibition_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='exhibition_image',
            field=models.ImageField(blank=True, null=True, upload_to='exhibition/'),
        ),
        migrations.AddField(
            model_name='idea',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='project_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='project_services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='team_emails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
