# Generated by Django 6.0 on 2026-04-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_idea_bootcamp_status_idea_evaluation_status'),
        ('ideas', '0006_idea_exhibition_date_idea_exhibition_image_and_more'),
    ]

    operations = [
    ]
