# Generated by Django 6.0.3 on 2026-04-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_merge_20260331_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
