# Generated by Django 6.0 on 2026-04-09 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_merge_20260402_1441'),
        ('volunteers', '0006_remove_consultationrequest_consultation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='bootcamp_status',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='evaluation_status',
        ),
        migrations.AddField(
            model_name='idea',
            name='team_status',
            field=models.CharField(choices=[('no_team', 'No Team'), ('team_building', 'Building Team'), ('team_full', 'Team Complete'), ('in_progress', 'In Progress')], default='no_team', max_length=50),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('WITHDRAWN', 'Withdrawn'), ('PRE_ACCEPTED', 'Pre Accepted (Bootcamp)'), ('BOOTCAMP', 'In Bootcamp'), ('BOOTCAMP_FAILED', 'Bootcamp Failed'), ('EVALUATION', 'In Evaluation'), ('EVALUATED', 'Evaluated'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('INCUBATION', 'In Incubation'), ('EXHIBITION', 'In Exhibition'), ('GRADUATED_POSITIVE', 'Graduated (Positive)'), ('GRADUATED_NEGATIVE', 'Graduated (Negative)')], default='DRAFT', max_length=50),
        ),
        migrations.CreateModel(
            name='IdeaAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ideas.idea')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skill_required', models.CharField(max_length=255)),
                ('members_needed', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to='ideas.idea')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteerprofile')),
                ('team_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_volunteers', to='ideas.teamrequest')),
            ],
        ),
    ]
