# Generated by Django 6.0.3 on 2026-04-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_merge_20260402_1441'),
        ('ideas', '0008_idea_sector_idea_target_audience'),
    ]

    operations = [
    ]
