# Generated by Django 6.0.3 on 2026-04-05 19:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_merge_20260405_1450'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='bootcamp_status',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='evaluation_status',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='target_audience',
        ),
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pre_accepted', 'Pre Accepted (Bootcamp)'), ('bootcamp', 'In Bootcamp'), ('bootcamp_failed', 'Bootcamp Failed'), ('evaluation', 'In Evaluation'), ('evaluated', 'Evaluated'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('incubation', 'In Incubation'), ('exhibition', 'In Exhibition'), ('graduated_positive', 'Graduated (Positive)'), ('graduated_negative', 'Graduated (Negative)')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='IdeaAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ideas.idea')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skill_required', models.CharField(max_length=255)),
                ('members_needed', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to='ideas.idea')),
            ],
        ),
    ]
