# Generated by Django 6.0.3 on 2026-04-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_remove_idea_bootcamp_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='sector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
