# Generated by Django 6.0 on 2026-04-16 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bootcamp', '0001_initial'),
        ('ideas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampabsencerequest',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_requests', to='ideas.idea'),
        ),
        migrations.AddField(
            model_name='bootcampabsencerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bootcampattendance',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='ideas.idea'),
        ),
        migrations.AddField(
            model_name='bootcampattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bootcampdecision',
            name='idea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_decision', to='ideas.idea'),
        ),
        migrations.AddField(
            model_name='bootcampsession',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootcamp_sessions', to='ideas.seasonphase'),
        ),
        migrations.AddField(
            model_name='bootcampsession',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_as_trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bootcampattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='bootcamp.bootcampsession'),
        ),
        migrations.AddField(
            model_name='bootcampabsencerequest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_requests', to='bootcamp.bootcampsession'),
        ),
        migrations.AlterUniqueTogether(
            name='bootcampattendance',
            unique_together={('session', 'idea')},
        ),
        migrations.AlterUniqueTogether(
            name='bootcampabsencerequest',
            unique_together={('session', 'idea')},
        ),
    ]
