# Generated by Django 6.0 on 2026-03-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0002_alter_bootcampsession_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootcampdecision',
            old_name='attendence_rate',
            new_name='attendance_rate',
        ),
    ]
