# Generated by Django 6.0.3 on 2026-05-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0003_alter_bootcampsession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampattendance',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bootcampattendance',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
