# Generated by Django 6.0.3 on 2026-03-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0003_rename_attendence_rate_bootcampdecision_attendance_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootcampdecision',
            old_name='notes',
            new_name='decision_note',
        ),
        migrations.AddField(
            model_name='bootcampsession',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bootcampsession',
            name='tasks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bootcampsession',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bootcampsession',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bootcampsession',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
