# Generated by Django 6.0.3 on 2026-03-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0004_rename_notes_bootcampdecision_decision_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcampsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcampsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
