# Generated by Django 6.0 on 2026-04-16 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning')], default='INFO', max_length=20)),
                ('action_type', models.CharField(blank=True, choices=[('OPEN_CHAT', 'Open Chat'), ('VIEW_REQUEST', 'View Request'), ('VIEW_IDEA', 'View Idea')], max_length=50, null=True)),
                ('target_role', models.CharField(blank=True, choices=[('VOLUNTEER', 'Volunteer'), ('IDEA_OWNER', 'Idea Owner'), ('TEAM_MEMBER', 'Team Member')], max_length=20, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('consultation_requested', 'Consultation Requested'), ('consultation_accepted', 'Consultation Accepted'), ('consultation_rejected', 'Consultation Rejected'), ('workshop_submitted', 'Workshop Submitted'), ('workshop_registered', 'Workshop Registered'), ('join_request_sent', 'Join Request'), ('evaluation_invitation_sent', 'Evaluation Invitation'), ('evaluation_invitation_accepted', 'Evaluation Accepted'), ('message_sent', 'Message'), ('account_suspended', 'Account Suspended')], max_length=100)),
                ('role', models.CharField(choices=[('VOLUNTEER', 'Volunteer'), ('IDEA_OWNER', 'Idea Owner'), ('USER', 'User')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event_name', 'role')},
            },
        ),
    ]
