# Generated by Django 6.0 on 2026-03-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_action_url_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('OPEN_CHAT', 'Open Chat'), ('VIEW_REQUEST', 'View Request'), ('VIEW_IDEA', 'View Idea')], max_length=50, null=True),
        ),
    ]
