# Generated by Django 6.0 on 2026-04-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(blank=True, choices=[('VOLUNTEER', 'Volunteer'), ('IDEA_OWNER', 'Idea Owner'), ('TEAM_MEMBER', 'Team Member')], max_length=20, null=True),
        ),
    ]
