# Generated by Django 6.0 on 2026-04-12 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationtemplate_notification_target_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('consultation_requested', 'Consultation Requested'), ('consultation_accepted', 'Consultation Accepted'), ('consultation_rejected', 'Consultation Rejected'), ('workshop_submitted', 'Workshop Submitted'), ('workshop_registered', 'Workshop Registered'), ('join_request_sent', 'Join Request'), ('evaluation_invitation_sent', 'Evaluation Invitation'), ('evaluation_invitation_accepted', 'Evaluation Accepted'), ('message_sent', 'Message'), ('account_suspended', 'Account Suspended')], max_length=100)),
                ('role', models.CharField(choices=[('VOLUNTEER', 'Volunteer'), ('IDEA_OWNER', 'Idea Owner'), ('USER', 'User')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event_name', 'role')},
            },
        ),
    ]
