# Generated by Django 6.0 on 2026-04-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
